# Generated by Django 4.1.7 on 2023-04-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Операция"
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция",
                "verbose_name_plural": "1 Операция",
            },
        ),
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Ресурс"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурс",
                "verbose_name_plural": "2 Ресурс",
            },
        ),
        migrations.CreateModel(
            name="RessourceOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.CharField(max_length=64)),
                (
                    "ressource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table_tgo.ressource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TGO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(db_index=True, max_length=150, verbose_name="ТГО"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "ТГО",
                "verbose_name_plural": "4 ТГО",
            },
        ),
        migrations.CreateModel(
            name="TGO_object",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table_tgo.operation",
                        verbose_name="Операция",
                    ),
                ),
                (
                    "ressource",
                    models.ManyToManyField(
                        through="table_tgo.RessourceOperation", to="table_tgo.ressource"
                    ),
                ),
                (
                    "tgo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table_tgo.tgo",
                        verbose_name="ТГО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект ТГО",
                "verbose_name_plural": "3 Объект ТГО",
            },
        ),
        migrations.AddField(
            model_name="ressourceoperation",
            name="tgo_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="table_tgo.tgo_object"
            ),
        ),
    ]
