# Generated by Django 4.1.7 on 2023-04-02 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("table_tgo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ressourceoperation",
            name="tgo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="table_tgo.tgo",
                verbose_name="ТГО",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ressourceoperation",
            name="count",
            field=models.CharField(max_length=64, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="ressourceoperation",
            name="ressource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="table_tgo.ressource",
                verbose_name="Ресурс",
            ),
        ),
        migrations.AlterField(
            model_name="ressourceoperation",
            name="tgo_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="table_tgo.tgo_object",
                verbose_name="Объект ТГО",
            ),
        ),
    ]
