# Generated by Django 4.1.7 on 2023-04-02 04:00

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("table_tgo", "0002_ressourceoperation_tgo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ressourceoperation",
            name="tgo_object",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="tgo",
                chained_model_field="tgo",
                on_delete=django.db.models.deletion.CASCADE,
                show_all=True,
                to="table_tgo.tgo_object",
                verbose_name="Объект ТГО",
            ),
        ),
    ]
