# Generated by Django 4.1.7 on 2023-04-03 06:29

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0002_alter_human_post_alter_schedulenotjob_human_and_more"),
        ("table_tgo", "0004_alter_ressourceoperation_ressource_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ressourceoperation",
            options={
                "ordering": ["id"],
                "verbose_name": "Ресурс для операции в ТГО",
                "verbose_name_plural": "5 Ресурсы для операции в ТГО",
            },
        ),
        migrations.AlterModelOptions(
            name="tgo",
            options={
                "ordering": ["id"],
                "verbose_name": "ТГО",
                "verbose_name_plural": "3 ТГО",
            },
        ),
        migrations.AlterModelOptions(
            name="tgo_object",
            options={
                "verbose_name": "Объект ТГО",
                "verbose_name_plural": "4 Объект ТГО",
            },
        ),
        migrations.AddField(
            model_name="ressourceoperation",
            name="office",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="table.office",
                verbose_name="Служба",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ressourceoperation",
            name="tgo_object",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="tgo",
                chained_model_field="tgo",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="res_operations",
                to="table_tgo.tgo_object",
                verbose_name="Объект ТГО",
            ),
        ),
    ]
