# Generated by Django 4.1.7 on 2023-04-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0002_alter_human_post_alter_schedulenotjob_human_and_more"),
        (
            "table_tgo",
            "0005_alter_ressourceoperation_options_alter_tgo_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tgo_office",
                        to="table.office",
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "tgo_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tgo_office",
                        to="table_tgo.tgo_object",
                        verbose_name="Объект ТГО",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tgo_object",
            name="office",
            field=models.ManyToManyField(
                through="table_tgo.OfficeMembers",
                to="table.office",
                verbose_name="Службы",
            ),
        ),
    ]
