# Generated by Django 4.1.7 on 2023-04-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0002_alter_human_post_alter_schedulenotjob_human_and_more"),
        ("table_tgo", "0006_officemembers_tgo_object_office"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ressourceoperation",
            name="office",
        ),
        migrations.RemoveField(
            model_name="tgo_object",
            name="office",
        ),
        migrations.AddField(
            model_name="ressource",
            name="office",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="table.office",
                verbose_name="Служба",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="OfficeMembers",
        ),
    ]
