# Generated by Django 4.1.7 on 2023-04-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table_tgo", "0008_alter_tgo_object_options_tgo_object_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ressourceoperation",
            name="count",
            field=models.PositiveIntegerField(verbose_name="Количество"),
        ),
    ]
