# Generated by Django 4.1.7 on 2023-04-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table_tgo", "0009_alter_ressourceoperation_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="ressourceoperation",
            name="time_end",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Конец"
            ),
        ),
        migrations.AddField(
            model_name="ressourceoperation",
            name="time_lenght",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Длительность"
            ),
        ),
        migrations.AddField(
            model_name="ressourceoperation",
            name="time_start",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Начало"
            ),
        ),
        migrations.AddField(
            model_name="tgo_object",
            name="time_end",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Конец"
            ),
        ),
        migrations.AddField(
            model_name="tgo_object",
            name="time_lenght",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Длительность"
            ),
        ),
        migrations.AddField(
            model_name="tgo_object",
            name="time_start",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="Начало"
            ),
        ),
    ]
