# Generated by Django 4.1.7 on 2023-04-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table_tgo", "0010_ressourceoperation_time_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ressourceoperation",
            name="time_end",
            field=models.CharField(
                blank=True, default="0", max_length=8, null=True, verbose_name="Конец"
            ),
        ),
        migrations.AlterField(
            model_name="ressourceoperation",
            name="time_lenght",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=8,
                null=True,
                verbose_name="Длительность",
            ),
        ),
        migrations.AlterField(
            model_name="ressourceoperation",
            name="time_start",
            field=models.CharField(
                blank=True, default="0", max_length=8, null=True, verbose_name="Начало"
            ),
        ),
        migrations.AlterField(
            model_name="tgo_object",
            name="time_end",
            field=models.CharField(
                blank=True, default="0", max_length=8, null=True, verbose_name="Конец"
            ),
        ),
        migrations.AlterField(
            model_name="tgo_object",
            name="time_lenght",
            field=models.CharField(
                blank=True,
                default="0",
                max_length=8,
                null=True,
                verbose_name="Длительность",
            ),
        ),
        migrations.AlterField(
            model_name="tgo_object",
            name="time_start",
            field=models.CharField(
                blank=True, default="0", max_length=8, null=True, verbose_name="Начало"
            ),
        ),
    ]
