# Generated by Django 4.1.7 on 2023-04-10 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("table_tgo", "0011_alter_ressourceoperation_time_end_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operation",
            options={
                "ordering": ["title"],
                "verbose_name": "Операция",
                "verbose_name_plural": "1 Операция",
            },
        ),
        migrations.AlterModelOptions(
            name="ressource",
            options={
                "ordering": ["title"],
                "verbose_name": "Ресурс",
                "verbose_name_plural": "2 Ресурс",
            },
        ),
        migrations.AddField(
            model_name="tgo",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tgo_object",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
