# Generated by Django 4.1.7 on 2023-04-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("table_tgo", "0012_alter_operation_options_alter_ressource_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tgo",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="tgo_object",
            old_name="user",
            new_name="author",
        ),
    ]
