# Generated by Django 4.1.7 on 2023-04-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_tgo', '0014_alter_ressourceoperation_tgo_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgo',
            name='tgo_length',
            field=models.CharField(default=1, max_length=10, verbose_name='Время'),
            preserve_default=False,
        ),
    ]
