# Generated by Django 4.1.7 on 2023-04-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_tgo', '0015_tgo_tgo_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgo',
            name='tgo_length',
            field=models.CharField(blank='True', default='', max_length=10, verbose_name='Время'),
        ),
    ]
