version: '3.10.6'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&Ñƒ
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/project
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      # - redis
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      -  ./.dump:/tmp/dump
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=marya0911SQL
      - POSTGRES_DB=statistics
      - POSTGRES_HOST_AUTH_METHOD=md5
  # redis:
  #   image: redis

volumes:
  postgres_data:
