# Generated by Django 4.1.7 on 2023-04-18 08:37

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airlines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "character_code",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Код"
                    ),
                ),
            ],
            options={
                "verbose_name": "Авиакомпания",
                "verbose_name_plural": "1 Авиакомпании",
            },
        ),
        migrations.CreateModel(
            name="Airplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.airlines",
                        verbose_name="Авиакомпания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Воздушное судно",
                "verbose_name_plural": "2 ВС",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "6 Города",
            },
        ),
        migrations.CreateModel(
            name="TypeCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип страны",
                "verbose_name_plural": "4 Типы стран",
            },
        ),
        migrations.CreateModel(
            name="TypeFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Тип рейса",
                "verbose_name_plural": "7 Типы рейсов",
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="№ рейса")),
                (
                    "airline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.airlines",
                        verbose_name="Аваиакомпания",
                    ),
                ),
                (
                    "airplane",
                    smart_selects.db_fields.ChainedForeignKey(
                        chained_field="airline",
                        chained_model_field="airline",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.airplane",
                        verbose_name="Воздушное судно",
                    ),
                ),
                (
                    "arrival",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrival",
                        to="timetable.city",
                        verbose_name="Прилет",
                    ),
                ),
                (
                    "departure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departure",
                        to="timetable.city",
                        verbose_name="Вылет",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.typeflight",
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейс",
                "verbose_name_plural": "8 Рейсы",
            },
        ),
        migrations.CreateModel(
            name="EquipmentAirplane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment",
                    models.CharField(max_length=50, verbose_name="Комплектация"),
                ),
                (
                    "seats",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Количество мест"
                    ),
                ),
                (
                    "airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.airplane",
                        verbose_name="ВС",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комплектация воздушного судна",
                "verbose_name_plural": "3 Комплектация ВС",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.typecountry",
                        verbose_name="Тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "5 Страны",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.country",
                verbose_name="Страна",
            ),
        ),
    ]
