# Generated by Django 4.1.7 on 2023-04-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="equipmentAirplane",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.equipmentairplane",
                verbose_name="Комплектация",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.airplane",
                verbose_name="Воздушное судно",
            ),
        ),
    ]
