# Generated by Django 4.1.7 on 2023-04-19 07:43

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_flight_equipmentairplane_alter_flight_airplane"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"verbose_name": "Рейс", "verbose_name_plural": "9 Рейсы"},
        ),
        migrations.AlterModelOptions(
            name="typeflight",
            options={
                "verbose_name": "Тип рейса",
                "verbose_name_plural": "8 Типы рейсов",
            },
        ),
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="airline",
                chained_model_field="airline",
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.airplane",
                verbose_name="Воздушное судно",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="equipmentAirplane",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="airplane",
                chained_model_field="airplane",
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.equipmentairplane",
                verbose_name="Комплектация",
            ),
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="timetable.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аэропорт",
                "verbose_name_plural": "7 Аэропорты",
            },
        ),
    ]
