# Generated by Django 4.1.7 on 2023-04-19 07:51

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_alter_flight_options_alter_typeflight_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="arrivalAirport",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="arrival",
                chained_model_field="city",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrivalAirport",
                to="timetable.airport",
                verbose_name="Аэропорт прилета",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="departurelAirport",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="departure",
                chained_model_field="city",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departurelAirport",
                to="timetable.airport",
                verbose_name="Аэропорт вылета",
            ),
            preserve_default=False,
        ),
    ]
