# Generated by Django 4.1.7 on 2023-04-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0005_ttimetablestatus_ttimetable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.airplane",
                verbose_name="Воздушное судно",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="arrivalAirport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrivalAirport",
                to="timetable.airport",
                verbose_name="Аэропорт прилета",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departurelAirport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departurelAirport",
                to="timetable.airport",
                verbose_name="Аэропорт вылета",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="equipmentAirplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.equipmentairplane",
                verbose_name="Комплектация",
            ),
        ),
    ]
