# Generated by Django 4.1.7 on 2023-04-21 08:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "timetable",
            "0006_alter_flight_airplane_alter_flight_arrivalairport_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ttimetable",
            new_name="Timetable",
        ),
        migrations.RenameModel(
            old_name="TtimetableStatus",
            new_name="TimetableStatus",
        ),
    ]
