# Generated by Django 4.1.7 on 2023-04-22 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timetable", "0007_rename_ttimetable_timetable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTimetable",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("arrival_time", models.TimeField(verbose_name="Прилет")),
                ("departure_time", models.TimeField(verbose_name="Вылет")),
                (
                    "next_day_status",
                    models.BooleanField(default=False, verbose_name="Следующий день"),
                ),
                (
                    "start_register_time",
                    models.TimeField(verbose_name="Начало Регистрации"),
                ),
                (
                    "end_register_time",
                    models.TimeField(verbose_name="Конец Регистрации"),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Начало действия"
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Конец действия"
                    ),
                ),
                ("tgo", models.CharField(max_length=150, verbose_name="ТГО")),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "monday",
                    models.BooleanField(default=False, verbose_name="Понедельник"),
                ),
                ("tuesday", models.BooleanField(default=False, verbose_name="Вторник")),
                ("wednesday", models.BooleanField(default=False, verbose_name="Среда")),
                (
                    "thursday",
                    models.BooleanField(default=False, verbose_name="Четверг"),
                ),
                ("friday", models.BooleanField(default=False, verbose_name="Пятнциа")),
                (
                    "saturday",
                    models.BooleanField(default=False, verbose_name="Суббота"),
                ),
                (
                    "sunday",
                    models.BooleanField(default=False, verbose_name="Воскресенье"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "airline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="timetable.airlines",
                        verbose_name="Аваиакомпания",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="timetable.flight",
                        verbose_name="Рейс",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetablestatusight",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="timetable.timetablestatus",
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "historical 11 Расписание",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
