# Generated by Django 4.1.7 on 2023-04-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0008_historicaltimetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltimetable",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="TimetableHistory",
                to="timetable.timetable",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicaltimetable",
            name="comment",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                null=True,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="comment",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                null=True,
                verbose_name="Комментарий",
            ),
        ),
    ]
