# Generated by Django 4.1.7 on 2023-04-27 04:19

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0011_historicaltimetable_timetablelist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="type_flight",
            field=models.CharField(default=1, max_length=150, verbose_name="Тип рейса"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="airline",
                chained_model_field="airline",
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.airplane",
                verbose_name="Воздушное судно",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="equipmentAirplane",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="airplane",
                chained_model_field="airplane",
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.equipmentairplane",
                verbose_name="Комплектация",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltimetable",
            name="flight",
            field=smart_selects.db_fields.ChainedForeignKey(
                blank=True,
                chained_field="airline",
                chained_model_field="airline",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="timetable.flight",
                verbose_name="Рейс",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="flight",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="airline",
                chained_model_field="airline",
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.flight",
                verbose_name="Рейс",
            ),
        ),
    ]
