# Generated by Django 4.1.7 on 2023-04-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_flight_type_flight_alter_flight_airplane_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'verbose_name': 'Аэропорт', 'verbose_name_plural': '3.3 Аэропорты'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': '3.2 Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': '3.1 Страны'},
        ),
        migrations.AlterModelOptions(
            name='equipmentairplane',
            options={'verbose_name': 'Комплектация воздушного судна', 'verbose_name_plural': '2.1 Комплектация ВС'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': '4.1 Рейсы'},
        ),
        migrations.AlterModelOptions(
            name='historicaltimetable',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'Версия', 'verbose_name_plural': 'historical 5.2 Расписание'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': '5.2 Расписание'},
        ),
        migrations.AlterModelOptions(
            name='timetablelist',
            options={'ordering': ['id'], 'verbose_name': 'Плановое расписание', 'verbose_name_plural': '5.1 Плановые расписания'},
        ),
        migrations.AlterModelOptions(
            name='timetablestatus',
            options={'verbose_name': 'Статус расписания', 'verbose_name_plural': '5 Статусы расписания'},
        ),
        migrations.AlterModelOptions(
            name='typecountry',
            options={'verbose_name': 'Тип страны', 'verbose_name_plural': '3 Типы стран'},
        ),
        migrations.AlterModelOptions(
            name='typeflight',
            options={'verbose_name': 'Тип рейса', 'verbose_name_plural': '4 Типы рейсов'},
        ),
    ]
