# Generated by Django 4.1.7 on 2023-04-27 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_tgo', '0015_tgo_tgo_length'),
        ('timetable', '0013_alter_airport_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltimetable',
            name='tgo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='table_tgo.tgo', verbose_name='ТГО'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_tgo.tgo', verbose_name='ТГО'),
        ),
    ]
