# Generated by Django 4.1.7 on 2023-03-22 07:43

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Human",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initials",
                    models.CharField(db_index=True, max_length=150, verbose_name="ФИО"),
                ),
            ],
            options={
                "verbose_name": "Человек",
                "verbose_name_plural": "3 Люди",
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Служба"
                    ),
                ),
            ],
            options={
                "verbose_name": "Служба",
                "verbose_name_plural": "1 Служба",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Должность"
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.office",
                        verbose_name="Служба",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "2 Должности",
            },
        ),
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "digital_code",
                    models.CharField(max_length=10, verbose_name="Цифровой код"),
                ),
                (
                    "character_code",
                    models.CharField(max_length=10, verbose_name="Сивольный код"),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Расшифровка")),
            ],
            options={
                "verbose_name": "Причина пропуска",
                "verbose_name_plural": "5 Причины пропуска",
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Смена",
                "verbose_name_plural": "6 Смены",
            },
        ),
        migrations.CreateModel(
            name="ScheduleNotJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Примечание"
                    ),
                ),
                (
                    "length_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Длительность"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(blank=True, null=True, verbose_name="Начало"),
                ),
                (
                    "date_end",
                    models.DateField(blank=True, null=True, verbose_name="Окончание"),
                ),
                (
                    "human",
                    smart_selects.db_fields.GroupedForeignKey(
                        group_field="post",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.human",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.office",
                        verbose_name="Служба",
                    ),
                ),
                (
                    "post",
                    smart_selects.db_fields.GroupedForeignKey(
                        group_field="office",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.post",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.reason",
                        verbose_name="Причина",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="table.shift",
                        verbose_name="Смена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные пропуска",
                "verbose_name_plural": "7 Данные пропусков",
            },
        ),
        migrations.AddField(
            model_name="human",
            name="office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="table.office",
                verbose_name="Служба",
            ),
        ),
        migrations.AddField(
            model_name="human",
            name="post",
            field=smart_selects.db_fields.ChainedForeignKey(
                chained_field="office",
                chained_model_field="office",
                on_delete=django.db.models.deletion.CASCADE,
                to="table.post",
                verbose_name="Должность",
            ),
        ),
    ]
