# Generated by Django 4.1.7 on 2023-04-23 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulenotjob',
            name='human',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.human', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='schedulenotjob',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.post', verbose_name='Должность'),
        ),
    ]
